// ============================================================
// COS Registration — Form Group Definitions
// ============================================================

import type { FormGroupDefinition } from '../../../../shared/domain/types';
import {
  TEST_FLAG_OPTIONS,
  INSTRUCTION_TYPE_OPTIONS,
  HH_TYPE_OPTIONS,
  ENERGISATION_STATUS_OPTIONS,
  PROFILE_CLASS_OPTIONS,
  MEASUREMENT_CLASS_OPTIONS,
  GSP_GROUP_OPTIONS,
  METER_TYPE_OPTIONS,
  MEASUREMENT_QUANTITY_OPTIONS,
  READING_TYPE_OPTIONS,
  BSC_VALIDATION_STATUS_OPTIONS,
  METER_READING_FLAG_OPTIONS,
  READING_METHOD_OPTIONS,
  REGULAR_READING_CYCLE_OPTIONS,
  METER_LOCATION_OPTIONS,
  RETRIEVAL_METHOD_OPTIONS,
  METER_REGISTER_TYPE_OPTIONS,
} from '../../industry-constants';

function localDateISO(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export const cosRegistrationFormGroups: FormGroupDefinition[] = [
  {
    id: 'file-settings',
    label: 'File Details',
    icon: '⚙',
    fields: [
      {
        id: 'testFlag',
        label: 'Test Flag',
        type: 'select',
        required: true,
        defaultValue: 'OPER',
        options: TEST_FLAG_OPTIONS,
        helpText: 'OPER = operational, TR06 = training',
      },
      {
        id: 'fileDate',
        label: 'File Date',
        type: 'date',
        required: true,
        defaultValue: localDateISO(),
        helpText: 'Date used in file headers (YYYYMMDD)',
      },
    ],
  },
  {
    id: 'css-registration',
    label: 'CSS Registration',
    icon: '🔗',
    fields: [
      {
        id: 'supplierGeneratedReference',
        label: 'Supplier Generated Reference',
        type: 'text',
        required: true,
        placeholder: 'SC000000549',
        helpText: 'Supplier-generated reference used in CSS02380_01 and CSS02300_01',
      },
      {
        id: 'cssCorrelationId',
        label: 'Correlation ID',
        type: 'text',
        required: true,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        helpText: 'GUID — correlationId shared across CSS02380_01 and CSS02300_01',
      },
      {
        id: 'registrationRequestId',
        label: 'Registration ID',
        type: 'text',
        required: true,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        helpText: 'GUID — registrationRequestId in CSS02380_01 / registrationId in CSS02300_01',
      },
      {
        id: 'timestampFormat',
        label: 'Timestamp Format',
        type: 'select',
        required: true,
        defaultValue: 'utc',
        options: [
          { value: 'utc',   label: 'UTC (e.g. 10:30:00.000Z)' },
          { value: 'local', label: 'Local system clock (e.g. 11:30:00.000)' },
        ],
        helpText: 'Controls the time part of registrationStatusFromDate in CSS messages',
      },
    ],
  },
  {
    id: 'market-parties',
    label: 'Market Parties',
    icon: '🏢',
    fields: [
      // ---- New Supplier ----
      { id: 'supplierRoleCode',          label: 'New Supplier Role Code',       type: 'text', required: true, defaultValue: 'X', maxLength: 1 },
      { id: 'supplierParticipantId',     label: 'New Supplier Participant ID',  type: 'text', required: true, defaultValue: 'GMTR' },
      // ---- Old Supplier ----
      { id: 'oldSupplierRoleCode',       label: 'Old Supplier Role Code',       type: 'text', required: true, defaultValue: 'X', maxLength: 1 },
      { id: 'oldSupplierParticipantId',  label: 'Old Supplier Participant ID',  type: 'text', required: true },
      // ---- Distributor / MPAS ----
      { id: 'distributorRoleCode',       label: 'Distributor / MPAS Role Code',       type: 'text', required: true, maxLength: 1 },
      { id: 'distributorParticipantId',  label: 'Distributor / MPAS Participant ID',  type: 'text', required: true },
      // ---- MOP ----
      { id: 'mopRoleCode',               label: 'New MOP Role Code',                type: 'text', required: true, defaultValue: 'M', maxLength: 1 },
      { id: 'mopParticipantId',          label: 'New MOP Participant ID',           type: 'text', required: true },
      // ---- Data Aggregator (DA) ----
      { id: 'daRoleCode',                label: 'New Data Aggregator Role Code',    type: 'text', required: true, defaultValue: 'B', maxLength: 1 },
      { id: 'daParticipantId',           label: 'New Data Aggregator Participant ID', type: 'text', required: true },
      // ---- Data Collector (DC) ----
      { id: 'dcRoleCode',                label: 'New Data Collector Role Code',     type: 'text', required: true, defaultValue: 'D', maxLength: 1 },
      { id: 'dcParticipantId',           label: 'New Data Collector Participant ID', type: 'text', required: true },
    ],
  },
  {
    id: 'supply-point',
    label: 'Supply Point',
    icon: '⚡',
    fields: [
      {
        id: 'mpan',
        label: 'MPAN',
        type: 'text',
        required: true,
        placeholder: '1200012345678',
        maxLength: 13,
      },
      {
        id: 'registrationDate',
        label: 'Registration Date (Supply Start)',
        type: 'date',
        required: true,
        helpText: 'New supply start / COS effective date',
      },
      {
        id: 'cosDate',
        label: 'Change of Supplier Date',
        type: 'date',
        required: true,
      },
      {
        id: 'msn',
        label: 'Meter Serial Number',
        type: 'text',
        required: true,
        placeholder: 'MSN12345678',
        helpText: 'Physical meter serial number',
      },
      { id: 'instructionNumber',      label: 'Instruction Number',           type: 'text',   required: true, placeholder: '17658' },
      { id: 'instructionType',        label: 'D0260 Instruction Type',       type: 'select', required: true, defaultValue: 'SP43', options: INSTRUCTION_TYPE_OPTIONS },
      { id: 'd0217InstructionType',   label: 'D0217 Instruction Type',       type: 'select', required: true, defaultValue: 'SP40', options: INSTRUCTION_TYPE_OPTIONS },
      { id: 'energisationStatus',     label: 'Energisation Status',          type: 'select', required: true, defaultValue: 'E',    options: ENERGISATION_STATUS_OPTIONS },
      { id: 'aggrType',               label: 'Data Aggregation Type',        type: 'select', required: true, options: HH_TYPE_OPTIONS },
      { id: 'collectorType',          label: 'Data Collector Type',          type: 'select', required: true, options: HH_TYPE_OPTIONS },
      { id: 'mopType',                label: 'Meter Operator Type',          type: 'select', required: true, options: HH_TYPE_OPTIONS },
      { id: 'postcode', label: 'Postcode', type: 'text', required: true, placeholder: 'GU1 4HN' },
      { id: 'contractRefMop', label: 'MOP Contract Reference', type: 'text', required: true, placeholder: 'GMTRMOP001', helpText: 'D0011 034[2] — MOP appointment contract reference' },
      { id: 'contractRefDc',  label: 'DC Contract Reference',  type: 'text', required: true, placeholder: 'GMTRDC001',  helpText: 'D0011 034[2] — DC appointment contract reference' },
      { id: 'contractRefDa',  label: 'DA Contract Reference',  type: 'text', required: true, placeholder: 'GMTRDA001',  helpText: 'D0011 034[2] — DA appointment contract reference' },
      {
        id: 'regularReadingCycle',
        label: 'Regular Reading Cycle',
        type: 'select',
        required: true,
        defaultValue: 'D',
        options: REGULAR_READING_CYCLE_OPTIONS,
        helpText: 'D0012 039[2]',
      },
    ],
  },
  {
    id: 'technical',
    label: 'Technical Attributes',
    icon: '📊',
    fields: [
      {
        id: 'profileClass',
        label: 'Profile Class',
        type: 'select',
        required: true,
        options: PROFILE_CLASS_OPTIONS,
      },
      {
        id: 'measurementClass',
        label: 'Measurement Class',
        type: 'select',
        required: true,
        options: MEASUREMENT_CLASS_OPTIONS,
      },
      {
        id: 'gspGroupId',
        label: 'GSP Group ID',
        type: 'select',
        required: true,
        options: GSP_GROUP_OPTIONS,
      },
      {
        id: 'llfClass',
        label: 'Line Loss Factor Class',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
        helpText: '3-digit LLFC code',
      },
      {
        id: 'ssc',
        label: 'Standard Settlement Configuration (SSC) Id',
        type: 'text',
        required: true,
        placeholder: '0000',
        maxLength: 4,
        helpText: 'SSC code (NHH only)',
      },
      {
        id: 'sconDate',
        label: 'Effective from Settlement Date (SCON)',
        type: 'date',
        required: false,
        syncFrom: 'cosDate',
        helpText: 'D0149 281[2] / D0150 289[2] — SSC effective from date',
      },
    ],
  },
  {
    id: 'meter-details',
    label: 'Meter Technical Details',
    icon: '🔧',
    fields: [
      {
        id: 'manufacturersMakeAndType',
        label: 'Manufacturers Make & Type',
        type: 'text',
        required: true,
        defaultValue: 'EDMI AtlasMk10A',
        placeholder: 'EDMI AtlasMk10A',
        helpText: 'D0150 290[5] — e.g. EDMI AtlasMk10A',
      },
      // D0150 290[18]
      {
        id: 'meterInstalledDate',
        label: 'Meter Installed Date',
        type: 'date',
        required: true,
        helpText: 'Date meter was installed — D0150 290[18]',
      },
      // D0150 291[0]
      {
        id: 'ctPrimaryRatio',
        label: 'CT Ratio',
        type: 'text',
        required: true,
        placeholder: '200/5',
        helpText: 'Current Transformer ratio — D0150 291[0] (e.g. 200/5 or 1 for NHH)',
      },
      // Remaining meter fields (D0052 / D0260)
      {
        id: 'meterType',
        label: 'Meter Type',
        type: 'select',
        required: true,
        options: METER_TYPE_OPTIONS,
      },
      {
        id: 'mtc',
        label: 'Meter Timeswitch Code',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
        helpText: '3-digit MTC code',
      },
      {
        id: 'timePatternRegiment',
        label: 'Time Pattern Regime',
        type: 'text',
        required: true,
        placeholder: '00001',
        maxLength: 5,
        helpText: '5-digit TPR code — D0149 778[0]',
      },
      {
        id: 'meterLocation',
        label: 'Meter Location',
        type: 'select',
        required: true,
        defaultValue: 'J',
        options: METER_LOCATION_OPTIONS,
        helpText: 'D0150 290[4] — where the meter is physically installed',
      },
      {
        id: 'meterAssetProviderId',
        label: 'Meter Asset Provider ID (MAP)',
        type: 'text',
        required: true,
        placeholder: 'UFUN',
        helpText: 'D0150 290[6] — MAP participant ID',
      },
      {
        id: 'certificationDate',
        label: 'Meter Certification Date',
        type: 'date',
        required: true,
        helpText: 'D0150 290[19] — date meter was certified',
      },
      {
        id: 'retrievalMethod',
        label: 'Retrieval Method',
        type: 'select',
        required: true,
        defaultValue: 'R',
        options: RETRIEVAL_METHOD_OPTIONS,
        helpText: 'D0150 290[23] — how meter readings are retrieved',
      },
      {
        id: 'retrievalMethodEffectiveDate',
        label: 'Retrieval Method Effective Date',
        type: 'date',
        required: true,
        helpText: 'D0150 290[24] — date retrieval method takes effect',
      },
    ],
  },
  {
    id: 'register-readings',
    label: 'Meter Registers & Meter Readings / Consumptions',
    icon: '📋',
    repeatable: true,
    fields: [
      {
        id: 'registerId',
        label: 'Register ID',
        type: 'text',
        required: true,
        maxLength: 2,
        helpText: "D0149 284[0] / D0150 293[0] — 'S' for NHH single register, or '01'",
      },
      {
        id: 'd0149RegisterCoefficient',
        label: 'Register Mapping Coefficient (D0149)',
        type: 'text',
        required: true,
        defaultValue: '1',
        placeholder: '1 or -1',
        helpText: "D0149 284[1] — '1' or '-1'",
      },
      {
        id: 'meterRegisterType',
        label: 'Meter Register Type',
        type: 'select',
        required: true,
        defaultValue: 'C',
        options: METER_REGISTER_TYPE_OPTIONS,
        helpText: 'D0150 293[1]',
      },
      {
        id: 'measurementQuantityId',
        label: 'Measurement Quantity ID',
        type: 'select',
        required: true,
        options: MEASUREMENT_QUANTITY_OPTIONS,
        helpText: 'D0150 293[2] / D0149 body',
      },
      {
        id: 'registerMappingCoefficient',
        label: 'Meter Register Multiplier (D0150)',
        type: 'text',
        required: true,
        defaultValue: '1.00',
        helpText: 'D0150 293[3] — NUM(9,2) e.g. 1.00',
      },
      {
        id: 'numberOfDigits',
        label: 'Number of Register Digits',
        type: 'text',
        required: true,
        placeholder: '7',
        helpText: 'D0150 293[5]',
      },
      {
        id: 'readingDate',
        label: 'Meter Reading Date',
        type: 'date',
        required: true,
        helpText: 'Date reading was taken',
      },
      {
        id: 'bscValidationStatus',
        label: 'BSC Validation Status',
        type: 'select',
        required: true,
        defaultValue: 'V',
        options: BSC_VALIDATION_STATUS_OPTIONS,
        helpText: 'D0010 026[1]',
      },
      {
        id: 'readingType',
        label: 'Reading Type',
        type: 'select',
        required: true,
        defaultValue: 'I',
        options: READING_TYPE_OPTIONS,
        helpText: 'D0010 028[1]',
      },
      {
        id: 'readingValue',
        label: 'Meter Reading',
        type: 'text',
        required: true,
        placeholder: '00000.0',
        helpText: 'D0010 030[2] — NUM(9,1) e.g. 256980.0',
      },
      {
        id: 'meterReadingFlag',
        label: 'Meter Reading Flag',
        type: 'select',
        required: true,
        defaultValue: 'T',
        options: METER_READING_FLAG_OPTIONS,
        helpText: 'D0010 030[5]',
      },
      {
        id: 'readingMethod',
        label: 'Reading Method',
        type: 'select',
        required: true,
        defaultValue: 'N',
        options: READING_METHOD_OPTIONS,
        helpText: 'D0010 030[6]',
      },
      {
        id: 'estimatedAnnualConsumption',
        label: 'Estimated Annual Consumption (kWh)',
        type: 'number',
        required: true,
        helpText: 'EAC in kWh',
      },
    ],
  },
];
