// ============================================================
// CoS Registration — Form Group Definitions
// ============================================================

import type { FormGroupDefinition } from '../../../../shared/domain/types';
import {
  TEST_FLAG_OPTIONS,
  PROFILE_CLASS_OPTIONS,
  MEASUREMENT_CLASS_OPTIONS,
  GSP_GROUP_OPTIONS,
  METER_TYPE_OPTIONS,
  NUMBER_OF_DIGITS_OPTIONS,
  MEASUREMENT_QUANTITY_OPTIONS,
  READING_TYPE_OPTIONS,
} from '../../industry-constants';

function localDateISO(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export const cosRegistrationFormGroups: FormGroupDefinition[] = [
  {
    id: 'file-settings',
    label: 'File Settings',
    icon: '⚙',
    fields: [
      {
        id: 'testFlag',
        label: 'Test Flag',
        type: 'select',
        required: true,
        defaultValue: 'OPER',
        options: TEST_FLAG_OPTIONS,
        helpText: 'OPER = operational, TR06 = training',
      },
      {
        id: 'fileDate',
        label: 'File Date',
        type: 'date',
        required: true,
        defaultValue: localDateISO(),
        helpText: 'Date used in file headers (YYYYMMDD)',
      },
    ],
  },
  {
    id: 'envelope-routing',
    label: 'Envelope Routing (ZHV)',
    icon: '🔀',
    fields: [
      {
        id: 'mpasRoleCode',
        label: 'MPAS Role Code',
        type: 'text',
        required: true,
        defaultValue: 'P',
        helpText: 'ZHV[4] — MPAS/Distributor role code (D0260, D0217 FROM)',
      },
      {
        id: 'mpasParticipantId',
        label: 'MPAS Participant ID',
        type: 'text',
        required: true,
        placeholder: 'EMEB',
        helpText: 'ZHV[5] — MPAS participant ID, varies per MPAN',
      },
      {
        id: 'supplierRoleCode',
        label: 'Supplier Role Code',
        type: 'text',
        required: true,
        defaultValue: 'X',
        helpText: 'Supplier role code — TO for most D-flows',
      },
      {
        id: 'supplierParticipantId',
        label: 'Supplier Participant ID',
        type: 'text',
        required: true,
        defaultValue: 'GMTR',
        helpText: 'Supplier participant ID',
      },
      {
        id: 'mopRoleCode',
        label: 'MOP Role Code',
        type: 'text',
        required: true,
        defaultValue: 'M',
        helpText: 'MOP role code (D0011/D0149/D0052 FROM)',
      },
      {
        id: 'mopParticipantId',
        label: 'MOP Participant ID',
        type: 'text',
        required: true,
        placeholder: 'BMET',
        helpText: 'MOP participant ID',
      },
      {
        id: 'daRoleCode',
        label: 'DA Role Code',
        type: 'text',
        required: true,
        defaultValue: 'B',
        helpText: 'DA role code (D0011 DA FROM)',
      },
      {
        id: 'daParticipantId',
        label: 'DA Participant ID',
        type: 'text',
        required: true,
        placeholder: 'UDMS',
        helpText: 'DA participant ID',
      },
      {
        id: 'dcRoleCode',
        label: 'DC Role Code',
        type: 'text',
        required: true,
        defaultValue: 'D',
        helpText: 'DC role code (D0011/D0010/D0150 FROM)',
      },
      {
        id: 'dcParticipantId',
        label: 'DC Participant ID',
        type: 'text',
        required: true,
        placeholder: 'UDMS',
        helpText: 'DC participant ID',
      },
    ],
  },
  {
    id: 'supply-point',
    label: 'Supply Point',
    icon: '⚡',
    fields: [
      {
        id: 'mpan',
        label: 'MPAN',
        type: 'text',
        required: true,
        placeholder: '1200012345678',
        maxLength: 13,
        helpText: '13-digit Meter Point Administration Number',
      },
      {
        id: 'msn',
        label: 'Meter Serial Number',
        type: 'text',
        required: true,
        placeholder: 'MSN12345678',
        helpText: 'Physical meter serial number',
      },
      {
        id: 'registrationDate',
        label: 'Registration Date (Supply Start)',
        type: 'date',
        required: true,
        helpText: 'New supply start / CoS effective date',
      },
      {
        id: 'cosDate',
        label: 'Change of Supplier Date',
        type: 'date',
        required: true,
        helpText: 'Date CoS is legally effective',
      },
    ],
  },
  {
    id: 'parties',
    label: 'Market Parties',
    icon: '🏢',
    fields: [
      {
        id: 'newSupplierId',
        label: 'New Supplier ID',
        type: 'text',
        required: true,
        placeholder: 'SP43',
        helpText: 'Gaining supplier party ID',
      },
      {
        id: 'oldSupplierId',
        label: 'Old Supplier ID',
        type: 'text',
        required: true,
        placeholder: 'EDF1',
        helpText: 'Losing supplier party ID',
      },
      {
        id: 'mobId',
        label: 'MOP (Meter Operator) ID',
        type: 'text',
        required: true,
        placeholder: 'MOP001',
        helpText: 'Meter Operator Business party ID',
      },
      {
        id: 'dcId',
        label: 'DC (Data Collector) ID',
        type: 'text',
        required: true,
        placeholder: 'HHDC001',
        helpText: 'Data Collector party ID',
      },
      {
        id: 'daId',
        label: 'DA (Data Aggregator) ID',
        type: 'text',
        required: true,
        placeholder: 'HHDA001',
        helpText: 'Data Aggregator party ID',
      },
      {
        id: 'distributorId',
        label: 'Distributor ID',
        type: 'text',
        required: true,
        placeholder: 'EMEB',
        helpText: 'Distribution network operator ID',
      },
    ],
  },
  {
    id: 'technical',
    label: 'Technical Attributes',
    icon: '📊',
    fields: [
      {
        id: 'profileClass',
        label: 'Profile Class',
        type: 'select',
        required: true,
        options: PROFILE_CLASS_OPTIONS,
      },
      {
        id: 'measurementClass',
        label: 'Measurement Class',
        type: 'select',
        required: true,
        options: MEASUREMENT_CLASS_OPTIONS,
      },
      {
        id: 'gspGroupId',
        label: 'GSP Group ID',
        type: 'select',
        required: true,
        options: GSP_GROUP_OPTIONS,
      },
      {
        id: 'llfClass',
        label: 'Line Loss Factor Class',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
        helpText: '3-digit LLFC code',
      },
      {
        id: 'ssc',
        label: 'Standard Settlement Config',
        type: 'text',
        required: false,
        placeholder: '0000',
        maxLength: 4,
        helpText: 'SSC code (NHH only)',
      },
    ],
  },
  {
    id: 'meter-details',
    label: 'Meter Technical Details',
    icon: '🔧',
    fields: [
      {
        id: 'meterType',
        label: 'Meter Type',
        type: 'select',
        required: true,
        options: METER_TYPE_OPTIONS,
      },
      {
        id: 'mtc',
        label: 'Meter Timeswitch Code',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
        helpText: '3-digit MTC code',
      },
      {
        id: 'meterMake',
        label: 'Meter Make',
        type: 'text',
        required: true,
        placeholder: 'LANDIS',
        helpText: 'Manufacturer name',
      },
      {
        id: 'meterModel',
        label: 'Meter Model',
        type: 'text',
        required: false,
        placeholder: 'E470',
        helpText: 'Model designation',
      },
      {
        id: 'ctPrimaryRatio',
        label: 'CT Primary Ratio',
        type: 'text',
        required: true,
        helpText: 'Current Transformer ratio (1 for NHH)',
      },
      {
        id: 'vtPrimaryRatio',
        label: 'VT Primary Ratio',
        type: 'text',
        required: true,
        helpText: 'Voltage Transformer ratio (1 for NHH)',
      },
      {
        id: 'numberOfDigits',
        label: 'Number of Digits',
        type: 'select',
        required: true,
        options: NUMBER_OF_DIGITS_OPTIONS,
      },
      {
        id: 'registerId',
        label: 'Register ID',
        type: 'text',
        required: true,
        maxLength: 2,
        helpText: 'Two-digit register identifier',
      },
      {
        id: 'measurementQuantityId',
        label: 'Measurement Quantity ID',
        type: 'select',
        required: true,
        options: MEASUREMENT_QUANTITY_OPTIONS,
        helpText: 'Type of measurement',
      },
      {
        id: 'timePatternRegiment',
        label: 'Time Pattern Regiment',
        type: 'text',
        required: true,
        maxLength: 5,
        helpText: '5-digit TPR code',
      },
      {
        id: 'scalingFactor',
        label: 'Scaling Factor',
        type: 'text',
        required: true,
        helpText: 'Meter scaling multiplier',
      },
      {
        id: 'meterInstalledDate',
        label: 'Meter Installed Date',
        type: 'date',
        required: true,
        helpText: 'Date meter was installed',
      },
    ],
  },
  {
    id: 'readings',
    label: 'Meter Readings & Consumption',
    icon: '📈',
    fields: [
      {
        id: 'readingDate',
        label: 'Meter Reading Date',
        type: 'date',
        required: true,
        helpText: 'Date reading was taken',
      },
      {
        id: 'readingType',
        label: 'Reading Type',
        type: 'select',
        required: true,
        options: READING_TYPE_OPTIONS,
        helpText: 'Read type as expected by D0149 / D0010',
      },
      {
        id: 'readingValue',
        label: 'Opening Meter Reading',
        type: 'text',
        required: true,
        placeholder: '00000',
        helpText: 'Numeric reading value',
      },
      {
        id: 'estimatedAnnualConsumption',
        label: 'Estimated Annual Consumption (kWh)',
        type: 'number',
        required: true,
        helpText: 'EAC in kWh',
      },
    ],
  },
];
