// ============================================================
// Energisation — Form Group Definitions
// ============================================================

import type { FormGroupDefinition } from '../../../../shared/domain/types';

function localDateISO(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

export const energisationFormGroups: FormGroupDefinition[] = [
  {
    id: 'file-settings',
    label: 'File Settings',
    icon: '⚙',
    fields: [
      {
        id: 'testFlag',
        label: 'Test Flag',
        type: 'select',
        required: true,
        defaultValue: 'OPER',
        options: [
          { label: 'OPER — Operational', value: 'OPER' },
          { label: 'TR06 — Training', value: 'TR06' },
        ],
      },
      {
        id: 'fileDate',
        label: 'File Date',
        type: 'date',
        required: true,
        defaultValue: localDateISO(),
      },
    ],
  },
  {
    id: 'supply-point',
    label: 'Supply Point',
    icon: '⚡',
    fields: [
      {
        id: 'mpan',
        label: 'MPAN',
        type: 'text',
        required: true,
        placeholder: '1200012345678',
        maxLength: 13,
        helpText: '13-digit MPAN',
      },
      {
        id: 'msn',
        label: 'Meter Serial Number',
        type: 'text',
        required: true,
        placeholder: 'MSN12345678',
      },
    ],
  },
  {
    id: 'parties',
    label: 'Market Parties',
    icon: '🏢',
    fields: [
      {
        id: 'supplierId',
        label: 'Supplier ID',
        type: 'text',
        required: true,
        placeholder: 'SP43',
      },
      {
        id: 'mobId',
        label: 'MOB (Meter Operator) ID',
        type: 'text',
        required: true,
        placeholder: 'MOB001',
      },
      {
        id: 'dcId',
        label: 'DC (Data Collector) ID',
        type: 'text',
        required: true,
        placeholder: 'HHDC001',
      },
      {
        id: 'distributorId',
        label: 'Distributor ID',
        type: 'text',
        required: true,
        placeholder: 'EMEB',
      },
    ],
  },
  {
    id: 'energisation-request',
    label: 'Energisation / De-energisation Request',
    icon: '🔌',
    fields: [
      {
        id: 'actionRequired',
        label: 'Action Required',
        type: 'select',
        required: true,
        defaultValue: 'E',
        options: [
          { label: 'E — Energise', value: 'E' },
          { label: 'D — De-energise', value: 'D' },
        ],
        helpText: 'Type of action to perform',
      },
      {
        id: 'requestedDate',
        label: 'Requested Date',
        type: 'date',
        required: true,
        helpText: 'Date energisation is required',
      },
      {
        id: 'reasonCode',
        label: 'Reason Code',
        type: 'select',
        required: true,
        defaultValue: '01',
        options: [
          { label: '01 — New Supply', value: '01' },
          { label: '02 — CoS', value: '02' },
          { label: '03 — Re-energisation', value: '03' },
          { label: '04 — Prepayment Reinstatement', value: '04' },
          { label: '05 — Safety', value: '05' },
          { label: '06 — Theft', value: '06' },
        ],
      },
      {
        id: 'accessDetails',
        label: 'Access Details',
        type: 'text',
        required: false,
        placeholder: 'Key safe code 1234',
        helpText: 'Any access instructions for MOB',
      },
      {
        id: 'contactName',
        label: 'Contact Name',
        type: 'text',
        required: false,
        placeholder: 'John Smith',
      },
      {
        id: 'contactNumber',
        label: 'Contact Number',
        type: 'text',
        required: false,
        placeholder: '07700900000',
      },
    ],
  },
  {
    id: 'technical',
    label: 'Technical Attributes',
    icon: '📊',
    fields: [
      {
        id: 'profileClass',
        label: 'Profile Class',
        type: 'select',
        required: true,
        options: [
          { label: '01 — Domestic Unrestricted', value: '01' },
          { label: '02 — Domestic Economy 7', value: '02' },
          { label: '03 — Non-Dom Unrestricted', value: '03' },
          { label: '04 — Non-Dom Economy 7', value: '04' },
          { label: '05 — Non-Dom MD LV', value: '05' },
          { label: '06 — Non-Dom MD HV', value: '06' },
          { label: '07 — Non-Dom MD LV Sub', value: '07' },
          { label: '08 — Non-Dom MD HV Sub', value: '08' },
        ],
      },
      {
        id: 'measurementClass',
        label: 'Measurement Class',
        type: 'select',
        required: true,
        options: [
          { label: 'A — Non Half-Hourly', value: 'A' },
          { label: 'B — Unrestricted Unmetered', value: 'B' },
          { label: 'C — Restricted Unmetered', value: 'C' },
          { label: 'D — Automatically read NHH', value: 'D' },
          { label: 'E — Half-Hourly', value: 'E' },
          { label: 'G — Deemed NHH', value: 'G' },
          { label: 'I — Half-Hourly AMR', value: 'I' },
        ],
      },
      {
        id: 'gspGroupId',
        label: 'GSP Group ID',
        type: 'select',
        required: true,
        options: [
          { label: '_A — Eastern', value: '_A' },
          { label: '_B — East Midlands', value: '_B' },
          { label: '_C — London', value: '_C' },
          { label: '_D — Merseyside & N Wales', value: '_D' },
          { label: '_E — Midlands', value: '_E' },
          { label: '_F — Northern', value: '_F' },
          { label: '_G — North Western', value: '_G' },
          { label: '_H — Southern', value: '_H' },
          { label: '_J — South Eastern', value: '_J' },
          { label: '_K — South Western', value: '_K' },
          { label: '_L — Yorkshire', value: '_L' },
          { label: '_M — South Scotland', value: '_M' },
          { label: '_N — North Scotland', value: '_N' },
          { label: '_P — South Wales', value: '_P' },
        ],
      },
      {
        id: 'llfClass',
        label: 'Line Loss Factor Class',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
      },
      {
        id: 'ssc',
        label: 'Standard Settlement Config',
        type: 'text',
        required: false,
        placeholder: '0000',
        maxLength: 4,
      },
    ],
  },
  {
    id: 'meter-details',
    label: 'Meter Technical Details',
    icon: '🔧',
    fields: [
      {
        id: 'meterType',
        label: 'Meter Type',
        type: 'select',
        required: true,
        options: [
          { label: 'S1A — Single Phase Credit', value: 'S1A' },
          { label: 'S1B — Single Phase Prepayment', value: 'S1B' },
          { label: 'E7A — Economy 7 Credit', value: 'E7A' },
          { label: 'E7B — Economy 7 Prepayment', value: 'E7B' },
          { label: 'H — Half-Hourly', value: 'H' },
          { label: 'NSS — Non Standard', value: 'NSS' },
        ],
      },
      {
        id: 'mtc',
        label: 'Meter Timeswitch Code',
        type: 'text',
        required: true,
        placeholder: '001',
        maxLength: 3,
      },
      {
        id: 'meterMake',
        label: 'Meter Make',
        type: 'text',
        required: true,
        placeholder: 'LANDIS',
      },
      {
        id: 'meterModel',
        label: 'Meter Model',
        type: 'text',
        required: false,
        placeholder: 'E470',
      },
      {
        id: 'ctPrimaryRatio',
        label: 'CT Primary Ratio',
        type: 'text',
        required: true,
      },
      {
        id: 'vtPrimaryRatio',
        label: 'VT Primary Ratio',
        type: 'text',
        required: true,
      },
      {
        id: 'numberOfDigits',
        label: 'Number of Digits',
        type: 'select',
        required: true,
        options: [
          { label: '4', value: '4' },
          { label: '5', value: '5' },
          { label: '6', value: '6' },
        ],
      },
      {
        id: 'registerId',
        label: 'Register ID',
        type: 'text',
        required: true,
        maxLength: 2,
      },
      {
        id: 'measurementQuantityId',
        label: 'Measurement Quantity ID',
        type: 'select',
        required: true,
        options: [
          { label: 'AI — Active Import', value: 'AI' },
          { label: 'RI — Reactive Import', value: 'RI' },
          { label: 'AQ — Active Export', value: 'AQ' },
        ],
      },
      {
        id: 'timePatternRegiment',
        label: 'Time Pattern Regiment',
        type: 'text',
        required: true,
        maxLength: 5,
      },
      {
        id: 'scalingFactor',
        label: 'Scaling Factor',
        type: 'text',
        required: true,
      },
      {
        id: 'meterInstalledDate',
        label: 'Meter Installed Date',
        type: 'date',
        required: true,
      },
    ],
  },
  {
    id: 'readings',
    label: 'Readings & Consumption',
    icon: '📈',
    fields: [
      {
        id: 'readingDate',
        label: 'Reading Date',
        type: 'date',
        required: true,
      },
      {
        id: 'readingType',
        label: 'Reading Type',
        type: 'select',
        required: true,
        options: [
          { label: 'A — Actual (physical read)', value: 'A' },
          { label: 'I — Initial (start of supply)', value: 'I' },
          { label: 'F — Final (end of supply)', value: 'F' },
          { label: 'P — Periodic (routine scheduled)', value: 'P' },
          { label: 'C — Customer self-read', value: 'C' },
          { label: 'E — Estimated', value: 'E' },
          { label: 'D — Deemed', value: 'D' },
        ],
        helpText: 'Read type as expected by D0149 / D0010',
      },
      {
        id: 'readingValue',
        label: 'Meter Reading',
        type: 'text',
        required: true,
        placeholder: '00000',
        helpText: 'Numeric reading value',
      },
      {
        id: 'estimatedAnnualConsumption',
        label: 'EAC (kWh)',
        type: 'number',
        required: true,
      },
    ],
  },
];
